### ISSUE TITLE
Predicting error when using deep_predict when using bacth_size != 1

### ISSUE THREAD

**Issue by QianyeYang** [DeepRegNet/DeepReg#482]
## Subject of the issue

When using `deepreg_prediction` command with --batch_size !=1, the error will occure probably because the number of samples in the test set can not be divisible by the number of batch_size. 

## Your environment

- DeepReg version 49c38a9b9fcfc344a4ef9bc5b5f4a7cc058b1545
(Which is quite old... I'm not sure if this bug still exists in later versions. )

**Comment by mathpluscode** [comment]
Hi @QianyeYang It can be possible, I forced it to 1 because of an error I think.

**Comment by mathpluscode** [comment]
@QianyeYang can you provide a full error log?

**Comment by QianyeYang** [comment]
> 
> 
> @QianyeYang can you provide a full error log? I'm testing with a demo, and it seems to be ok.

2020-10-26 01:18:47.233327: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at conv_grad_ops_3d.cc:1169 : Invalid argument: Conv3DBackpropInputOp: input and out_backprop must have the same batch sizeinput batch: 4outbackprop batch: 2 batch_dim: 0
Traceback (most recent call last):
  File "/home/qianye/miniconda3/envs/deepreg/bin/deepreg_predict", line 33, in <module>
    sys.exit(load_entry_point('deepreg', 'console_scripts', 'deepreg_predict')())
  File "/raid/candi/QianyeYang/DeepReg/deepreg/predict.py", line 438, in main
    args.png,
  File "/raid/candi/QianyeYang/DeepReg/deepreg/predict.py", line 340, in predict
    save_png=save_png,
  File "/raid/candi/QianyeYang/DeepReg/deepreg/predict.py", line 87, in predict_on_dataset
    outputs_dict = model.predict(x=inputs_dict)
  File "/home/qianye/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 88, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/qianye/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1268, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "/home/qianye/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/qianye/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 618, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/qianye/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/qianye/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/home/qianye/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/qianye/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/home/qianye/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Conv3DBackpropInputOp: input and out_backprop must have the same batch sizeinput batch: 4outbackprop batch: 2 batch_dim: 0
	 [[node DDFRegistrationModelWithLabel/local_net/local_net_up_sample_resnet_block/deconv3d_block/deconv3d/conv3d_transpose/conv3d_transpose (defined at raid/candi/QianyeYang/DeepReg/deepreg/model/layer.py:177) ]] [Op:__inference_predict_function_10107]

Errors may have originated from an input operation.
Input Source operations connected to node DDFRegistrationModelWithLabel/local_net/local_net_up_sample_resnet_block/deconv3d_block/deconv3d/conv3d_transpose/conv3d_transpose:
 DDFRegistrationModelWithLabel/local_net/conv3d_block_6/activation_9/Relu (defined at raid/candi/QianyeYang/DeepReg/deepreg/model/layer.py:18)

Function call stack:
predict_function

**Comment by mathpluscode** [comment]
@QianyeYang I confirm that it's a bug and we can reproduce it with demo data:

1. Copy one sample in `DeepReg/data/test/nifti/unpaired/test/` for both images and labels so that we have three samples in total.
2. Run `deepreg_train --gpu "" --config_path config/unpaired_labeled_ddf.yaml --log_dir test`
3. Run `deepreg_predict --gpu "" --ckpt_path logs/test/save/weights-epoch2.ckpt --mode test -b 2`

Then the error will appear

```
(deepreg) mathpluscode@mathpluscode-XPS-13-9300:~/Git/DeepReg$ deepreg_predict --gpu "" --ckpt_path logs/test/save/weights-epoch2.ckpt --mode test -b 2
2020-10-30 23:18:08.558102: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:root:sample_label is not used in predict. It is True if and only if mode == 'train'.
2020-10-30 23:18:09.789639: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-10-30 23:18:09.789663: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-10-30 23:18:09.789678: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mathpluscode-XPS-13-9300): /proc/driver/nvidia/version does not exist
2020-10-30 23:18:09.791509: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-30 23:18:09.816668: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1497600000 Hz
2020-10-30 23:18:09.817186: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55dead4dd2a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-30 23:18:09.817213: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-30 23:18:19.790193: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_grad_ops_3d.cc:353 : Invalid argument: Conv3DBackpropInputOp: input and out_backprop must have the same batch sizeinput batch: 2outbackprop batch: 1 batch_dim: 0
Traceback (most recent call last):
  File "/home/mathpluscode/miniconda3/envs/deepreg/bin/deepreg_predict", line 33, in <module>
    sys.exit(load_entry_point('deepreg', 'console_scripts', 'deepreg_predict')())
  File "/home/mathpluscode/Git/DeepReg/deepreg/predict.py", line 435, in main
    save_png=args.png,
  File "/home/mathpluscode/Git/DeepReg/deepreg/predict.py", line 334, in predict
    save_png=save_png,
  File "/home/mathpluscode/Git/DeepReg/deepreg/predict.py", line 81, in predict_on_dataset
    outputs_dict = model.predict(x=inputs_dict)
  File "/home/mathpluscode/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 130, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/mathpluscode/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1599, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "/home/mathpluscode/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/mathpluscode/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 814, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/mathpluscode/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/mathpluscode/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/mathpluscode/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/mathpluscode/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/mathpluscode/miniconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Conv3DBackpropInputOp: input and out_backprop must have the same batch sizeinput batch: 2outbackprop batch: 1 batch_dim: 0
         [[node DDFRegistrationModelWithLabel/local_net/local_net_up_sample_resnet_block/deconv3d_block/deconv3d/conv3d_transpose/conv3d_transpose (defined at /Git/DeepReg/deepreg/model/layer.py:177) ]] [Op:__inference_predict_function_11018]

Errors may have originated from an input operation.
Input Source operations connected to node DDFRegistrationModelWithLabel/local_net/local_net_up_sample_resnet_block/deconv3d_block/deconv3d/conv3d_transpose/conv3d_transpose:
 DDFRegistrationModelWithLabel/local_net/conv3d_block_8/activation_12/Relu (defined at /Git/DeepReg/deepreg/model/layer.py:18)

Function call stack:
predict_function

```
