### ISSUE TITLE
import error after latest git pull (main branch)

### ISSUE THREAD

**Issue by ciphercharly** [DeepRegNet/DeepReg#689]
got a new error related to the pydot package, which is in the deepreg virtual environment so I am not sure why this happens
(tried to re-install it and same result)

Total params: 494,489
Trainable params: 493,689
Non-trainable params: 800
__________________________________________________________________________________________________
None
Traceback (most recent call last):
  File "demos/paired_MMIV/demo_train.py", line 29, in <module>
    log_dir=log_dir,
  File "/home/charlie/3DREG-tests/DeepReg/deepreg/train.py", line 141, in train
    model.plot_model(output_dir=log_dir)
  File "/home/charlie/3DREG-tests/DeepReg/deepreg/model/network.py", line 279, in plot_model
    expand_nested=False,
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/utils/vis_utils.py", line 306, in plot_model
    dpi=dpi)
  File "/home/charlie/anaconda3/envs/deepreg/lib/python3.7/site-packages/tensorflow/python/keras/utils/vis_utils.py", line 114, in model_to_dot
    raise ImportError(message)
ImportError: ('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')

**Comment by mathpluscode** [comment]
@ciphercharly we just fixed it.

The reason was we are now plotting model structure, which requires a new dependency `graphviz` that can not be installed via pip, as stated in the error message.

In PR #686, we've caught the error ;)

Please let us know if this solves your problem or not.

**Comment by mathpluscode** [comment]
Otherwise, you can also install `graphviz` following the guide here https://deepreg.readthedocs.io/en/latest/getting_started/install.html

**Comment by ciphercharly** [comment]
the code runs now, thanks a lot! and at the moment I do not need ``graphviz``
